version: '3.8'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Admin123*_!"  
      ACCEPT_EULA: "Y"
  
  database_seed:
    depends_on : [sqlserver]
    build: 
     context : ./WhoIs.DBSeed/Database/
     dockerfile: Dockerfile

  face_recognition:
    image: face_service
    depends_on : [database_seed]
    ports:
      - "8080:8080"
    volumes:
      - ./faces:/root/faces

  whoisapi:
    image: whoisapi
    depends_on : [database_seed]
    ports:
      - "32787:8080"
    volumes:
      - ./faces:/app/faces

  seq_log:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5341:80"

  whoisui:
    image: whoisui
    depends_on : [database_seed]
    ports:
      - "4000:80"
